CREATE TABLE countries (
    id VARCHAR(255) PRIMARY KEY
);

INSERT INTO countries (id) VALUES
  ('Angola'),
  ('Argentina'),
  ('Australia'),
  ('Austria'),
  ('Azerbaijan'),
  ('Bahrain'),
  ('Bangladesh'),
  ('Barbados'),
  ('Belgium'),
  ('Brazil'),
  ('Bulgaria'),
  ('Canada'),
  ('Chile'),
  ('China'),
  ('Colombia'),
  ('Costa Rica'),
  ('Cyprus'),
  ('Czechia'),
  ('Denmark'),
  ('Dominican Republic'),
  ('Ecuador'),
  ('Egypt'),
  ('El Salvador'),
  ('Estonia'),
  ('Finland'),
  ('France'),
  ('Germany'),
  ('Ghana'),
  ('Greece'),
  ('Hong Kong'),
  ('Hungary'),
  ('India'),
  ('Indonesia'),
  ('Ireland'),
  ('Israel'),
  ('Italy'),
  ('Jamaica'),
  ('Japan'),
  ('Jordan'),
  ('Kazakhstan'),
  ('Kenya'),
  ('Latvia'),
  ('Lebanon'),
  ('Lithuania'),
  ('Luxembourg'),
  ('Malaysia'),
  ('Malta'),
  ('Mexico'),
  ('Morocco'),
  ('Netherlands'),
  ('New Zealand'),
  ('Nigeria'),
  ('Norway'),
  ('Oman'),
  ('Pakistan'),
  ('Panama'),
  ('Paraguay'),
  ('Peru'),
  ('Philippines'),
  ('Poland'),
  ('Portugal'),
  ('Qatar'),
  ('Republic of Korea'),
  ('Romania'),
  ('Russian Federation'),
  ('Saudi Arabia'),
  ('Serbia'),
  ('Singapore'),
  ('Slovak Republic'),
  ('Slovenia'),
  ('South Africa'),
  ('Spain'),
  ('Sri Lanka'),
  ('Sweden'),
  ('Switzerland'),
  ('Thailand'),
  ('Türkiye'),
  ('Uganda'),
  ('Ukraine'),
  ('United Arab Emirates'),
  ('United Kingdom'),
  ('United States'),
  ('Uruguay'),
  ('Vietnam'),
  ('Zambia');
